# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    build_app(scheme: "RefdsBudget")
    upload_to_app_store
    xcode_select "/Applications/Xcode.app"
   end
end

platform :ios do
  desc "Push a new beta build to the Test Flight"
  lane :beta do
    build_app(scheme: "RefdsBudget")
    upload_to_testflight
    xcode_select "/Applications/Xcode.app"
  end
end
