default_platform(:ios)

platform :ios do
  desc "🚀 Prepare and deploy a polished app release, ready to shine in the App Store!"
  lane :release do
    sync_code_signing(type: "appstore")
    build_app(scheme: "MyApp")
    upload_to_testflight
    slack(message: "Successfully distributed a new beta build")
  end

  desc "🔧 Builds your app with precision, creating a flawless version ready for testing or release!"
  lane :build do
    build_app(scheme: "Budget Production")
    xcode_select "/Applications/Xcode.app"
   end

  desc "🧪 Runs all tests to ensure your app is flawless, stable, and ready for deployment!"
  lane :tests do
    run_tests(scheme: "Budget Production")
  end

end
